  function onStartGame() {
    alert("huh?")
    alert("uhm... hi???")
    alert("who are you?")
    let name = prompt("what is your name?")
    alert(`oh, uhm.. hi ${name}`) 
    alert("what are you doing here?")
    alert("how did you get here...?")
    alert("okey, let's not talk about that right now")
    let anwser = prompt(`uhm...are you okey ${name}?`)
    alert("I guess that's good?")
    alert("oh yeah, I forgot to tell you my name!")
    alert("my name is Niko, I uhm... live here")
    let resp = prompt("you look really confuse,,, are you sure u'r allright?")
    alert(`${resp} you say... okey... fine`)
    alert("I belive you wonder where you are...")
    alert("this is the void... the spaces in between universes")
    alert("it was created to trap the wizard, but as you might have seen... there's no wizard here... only me")
    alert("I'm not sure why I'm here... but.... ")
    alert("?")
    alert("I just wondered if you know how to leave?")
  }